# Generated by Django 4.2.16 on 2024-12-02 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='ads',
            name='time_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
