# Generated by Django 4.2.16 on 2024-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_onetimecode_alter_ads_author_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='ad_images'),
        ),
        migrations.AddField(
            model_name='ads',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
