# Generated by Django 4.2.16 on 2024-12-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_reply_delete_onetimecode_remove_ads_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='category',
        ),
        migrations.AddField(
            model_name='ads',
            name='category',
            field=models.ManyToManyField(to='board.category'),
        ),
    ]
